name: Update Homebrew Formula On Release

on:
  push:
    tags:
      - '*'

jobs:
  update-homebrew-formula-on-release:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.TOKEN}}
          tap: ludusrusso/core
          formula: clusterctl
          tag: ${{github.ref}}
          revision: ${{github.sha}}
